import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";


const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="daw-waveform"
      className={`${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
